latestt

diff --git a/1script b/1script
--- a/1script
+++ b/1script
@@ -4,14 +4,18 @@
 
 . mutil.sh
 
-f="$(which "$1")"
-if ! [[ -f "$f" ]] ; then
-  if [[ -d "$1" ]] ; then
-    ee 1 "$f" # Open a directory instead.
-    exit 0
+if [[ -f "$1" ]] ; then
+  f="$1"
+else
+  f="$(which "$1")"
+  if ! [[ -f "$f" ]] ; then
+    if [[ -d "$1" ]] ; then
+      ee 1 "$f" # Open a directory instead.
+      exit 0
+    fi
+    echo "$0: '$1' not found." 1>&2
+    exit 1
   fi
-  echo "$0: '$1' not found." 1>&2
-  exit 1
 fi
 
 t="$(file -L "$f")"
