latest

diff --git a/bash-command-not-found b/bash-command-not-found
--- a/bash-command-not-found
+++ b/bash-command-not-found
@@ -1,18 +1,32 @@
+
 function command_not_found_handle() {
-    local command=$1
+    . "$BASH_SOURCE" || return 99
+    command_not_found_handle_raw "$@"
+}
+
+function command_not_found_handle_raw() {
+    local command="$1"
+
+    local me="[command_not_found_handle in $BASH_SOURCE] "
 
     # Auto git checkout.
     if is-git-branch "$command" ; then
-        echo "git checkout $command"
+        byellow "$me -- git checkout $command"
         ee git checkout "$command"
         return $?
     fi
 
-    # Try to add +x, but it doesn't work because this hook isn't called.
-    if x "$command" ; then
-        return 0
+#    # Try to add +x, but it doesn't work because this hook isn't called.
+#    if x "$command" ; then
+#        return 0
+#    fi
+
+    if [[ "$command" =~ ^test[A-Z] ]] ; then
+        byellow "$me -- running \"$command\" with \`a\`"
+        a "$command"
+        return $?
     fi
 
-    echo "bash: $command: command not found"
+    echo "bash: $command: command not found. (update $BASH_SOURCE to add a handler)"
     return 127
 }
