Moving -p to filter

diff --git a/filter b/filter
--- a/filter
+++ b/filter
@@ -34,6 +34,9 @@
 #
 # Also if a pattern starts with an @, then only print the lines that match it.
 #
+# Also it accepts multiple -p options to highlight output.
+#  -p PATTERN: Highlight a pattern with the hl command.
+#
 set -e
 
 . mutil.sh
@@ -42,6 +45,28 @@ args=("$@")
 
 # Find the first , in the argument list.
 comma_index=-1
+
+# Extract "-p pattern"s.
+hl_opts=()
+
+while [[ "$1" =~ ^- ]] ; do
+  case "$1" in
+    -p)
+      hl_opts=("-p" "$2")
+      shift 2
+      ;;
+    *)
+      echo "$0: Invalid option '$1'" 1>&2
+      exit 1
+  esac
+done
+
+hl=cat
+if (( ${#hl_opts[@]} > 0 )) ; then
+  hl=(hl "${hl_opts[@]}")
+fi
+
+# Find , to extract filters.
 
 args=("$@")
 for (( i = 0; i < ${#args[@]}; i++ )) ; do
@@ -62,6 +87,11 @@ else
   filter=("${args[@]:$(($comma_index+1))}")
 fi
 
+if (( ${#command[@]} == 0 )) ; then
+  echo "$0: Missing command" 1>&2
+  exit 1
+fi
+
 {
   byellow -n "Command: "
   bcyan "$(shescape "${command[@]}")"
@@ -71,4 +101,4 @@ fi
 } 1>&2
 
 # Execute the command and feed it to filter.rb
-"${command[@]}" | $0.rb "${filter[@]}"
+"${command[@]}" |& $0.rb "${filter[@]}" | "${hl[@]}"
